NEIGHBORHOOD_LIST = [
  ("Prefer Not To Say","Prefer Not To Say"),
  ("Aleppo Township","Aleppo Township"),
  ("Allegheny Center","Allegheny Center"),
  ("Allegheny West","Allegheny West"),
  ("Allentown","Allentown"),
  ("Arlington","Arlington"),
  ("Arlington Heights","Arlington Heights"),
  ("Aspinwall Borough","Aspinwall Borough"),
  ("Avalon Borough","Avalon Borough"),
  ("Baldwin Borough","Baldwin Borough"),
  ("Baldwin Township","Baldwin Township"),
  ("Banksville","Banksville"),
  ("Bedford Dwellings","Bedford Dwellings"),
  ("Beechview","Beechview"),
  ("Bell Acres Borough","Bell Acres Borough"),
  ("Bellevue Borough","Bellevue Borough"),
  ("Beltzhoover","Beltzhoover"),
  ("Ben Avon Borough","Ben Avon Borough"),
  ("Ben Avon Heights Borough","Ben Avon Heights Borough"),
  ("Bethel Park Municipality","Bethel Park Municipality"),
  ("Blawnox Borough","Blawnox Borough"),
  ("Bloomfield","Bloomfield"),
  ("Bluff","Bluff"),
  ("Bon Air","Bon Air"),
  ("Brackenridge Borough","Brackenridge Borough"),
  ("Braddock Borough","Braddock Borough"),
  ("Braddock Hills Borough","Braddock Hills Borough"),
  ("Bradford Woods Borough","Bradford Woods Borough"),
  ("Brentwood Borough","Brentwood Borough"),
  ("Bridgeville Borough","Bridgeville Borough"),
  ("Brighton Heights","Brighton Heights"),
  ("Brookline","Brookline"),
  ("California-Kirkbride","California-Kirkbride"),
  ("Carnegie Borough","Carnegie Borough"),
  ("Carrick","Carrick"),
  ("Castle Shannon Borough","Castle Shannon Borough"),
  ("Central Lawrenceville","Central Lawrenceville"),
  ("Central Northside","Central Northside"),
  ("Central Oakland","Central Oakland"),
  ("Chalfant Borough","Chalfant Borough"),
  ("Chartiers City","Chartiers City"),
  ("Chateau","Chateau"),
  ("Cheswick Borough","Cheswick Borough"),
  ("Churchill Borough","Churchill Borough"),
  ("Citywide","Citywide"),
  ("Clairton","Clairton"),
  ("Collier Township","Collier Township"),
  ("Coraopolis Borough","Coraopolis Borough"),
  ("Crafton Borough","Crafton Borough"),
  ("Crafton Heights","Crafton Heights"),
  ("Crawford-Roberts","Crawford-Roberts"),
  ("Crescent Township","Crescent Township"),
  ("Dormont Borough","Dormont Borough"),
  ("Downtown","Downtown"),
  ("Dravosburg Borough","Dravosburg Borough"),
  ("Duquesne","Duquesne"),
  ("Duquesne Heights","Duquesne Heights"),
  ("East Allegheny","East Allegheny"),
  ("East Carnegie","East Carnegie"),
  ("East Deer Township","East Deer Township"),
  ("East Hills","East Hills"),
  ("East Liberty","East Liberty"),
  ("East McKeesport Borough","East McKeesport Borough"),
  ("East Pittsburgh Borough","East Pittsburgh Borough"),
  ("Edgewood Borough","Edgewood Borough"),
  ("Edgeworth Borough","Edgeworth Borough"),
  ("Elizabeth Borough","Elizabeth Borough"),
  ("Elizabeth Township","Elizabeth Township"),
  ("Elliott","Elliott"),
  ("Emsworth Borough","Emsworth Borough"),
  ("Esplen","Esplen"),
  ("Etna Borough","Etna Borough"),
  ("Fairywood","Fairywood"),
  ("Fawn Township","Fawn Township"),
  ("Findlay Township","Findlay Township"),
  ("Fineview","Fineview"),
  ("Forest Hills Borough","Forest Hills Borough"),
  ("Forward Township","Forward Township"),
  ("Fox Chapel Borough","Fox Chapel Borough"),
  ("Franklin Park Borough","Franklin Park Borough"),
  ("Frazer Township","Frazer Township"),
  ("Friendship","Friendship"),
  ("Garfield","Garfield"),
  ("Glassport Borough","Glassport Borough"),
  ("Glen Hazel","Glen Hazel"),
  ("Glen Osborne Borough","Glen Osborne Borough"),
  ("Glenfield Borough","Glenfield Borough"),
  ("Green Tree Borough","Green Tree Borough"),
  ("Greenfield","Greenfield"),
  ("Hampton Township","Hampton Township"),
  ("Harmar Township","Harmar Township"),
  ("Harrison Township","Harrison Township"),
  ("Hays","Hays"),
  ("Haysville Borough","Haysville Borough"),
  ("Hazelwood","Hazelwood"),
  ("Heidelberg Borough","Heidelberg Borough"),
  ("Highland Park","Highland Park"),
  ("Homestead Borough","Homestead Borough"),
  ("Homewood North","Homewood North"),
  ("Homewood South","Homewood South"),
  ("Homewood West","Homewood West"),
  ("Indiana Township","Indiana Township"),
  ("Ingram Borough","Ingram Borough"),
  ("Jefferson Hills Borough","Jefferson Hills Borough"),
  ("Kennedy Township","Kennedy Township"),
  ("Kilbuck Township","Kilbuck Township"),
  ("Knoxville","Knoxville"),
  ("Larimer","Larimer"),
  ("Leet Township","Leet Township"),
  ("Leetsdale Borough","Leetsdale Borough"),
  ("Liberty Borough","Liberty Borough"),
  ("Lincoln Borough","Lincoln Borough"),
  ("Lincoln Place","Lincoln Place"),
  ("Lincoln-Lemington-Belmar","Lincoln-Lemington-Belmar"),
  ("Lower Lawrenceville","Lower Lawrenceville"),
  ("Manchester","Manchester"),
  ("Marshall Township","Marshall Township"),
  ("Marshall-Shadeland","Marshall-Shadeland"),
  ("McCandless Township","McCandless Township"),
  ("McDonald Borough","McDonald Borough"),
  ("McKees Rocks Borough","McKees Rocks Borough"),
  ("McKeesport","McKeesport"),
  ("Middle Hill","Middle Hill"),
  ("Millvale Borough","Millvale Borough"),
  ("Monroeville Municipality","Monroeville Municipality"),
  ("Moon Township","Moon Township"),
  ("Morningside","Morningside"),
  ("Mount Lebanon Township","Mount Lebanon Township"),
  ("Mount Oliver Borough","Mount Oliver Borough"),
  ("Mount Washington","Mount Washington"),
  ("Mt. Oliver","Mt. Oliver"),
  ("Munhall Borough","Munhall Borough"),
  ("Neville Township","Neville Township"),
  ("New Homestead","New Homestead"),
  ("North Braddock Borough","North Braddock Borough"),
  ("North Fayette Township","North Fayette Township"),
  ("North Oakland","North Oakland"),
  ("North Shore","North Shore"),
  ("North Versailles Township","North Versailles Township"),
  ("Northview Heights","Northview Heights"),
  ("O Hara Township","O Hara Township"),
  ("Oakdale Borough","Oakdale Borough"),
  ("Oakmont Borough","Oakmont Borough"),
  ("Oakwood","Oakwood"),
  ("Ohio Township","Ohio Township"),
  ("Overbrook","Overbrook"),
  ("Penn Hills Municipality","Penn Hills Municipality"),
  ("Pennsbury Village Borough","Pennsbury Village Borough"),
  ("Perry North","Perry North"),
  ("Perry South","Perry South"),
  ("Pine Township","Pine Township"),
  ("Pitcairn Borough","Pitcairn Borough"),
  ("Pleasant Hills Borough","Pleasant Hills Borough"),
  ("Plum Borough","Plum Borough"),
  ("Point Breeze","Point Breeze"),
  ("Point Breeze North","Point Breeze North"),
  ("Polish Hill","Polish Hill"),
  ("Port Vue Borough","Port Vue Borough"),
  ("Rankin Borough","Rankin Borough"),
  ("Regent Square","Regent Square"),
  ("Reserve Township","Reserve Township"),
  ("Richland Township","Richland Township"),
  ("Ridgemont","Ridgemont"),
  ("Robinson Township","Robinson Township"),
  ("Ross Township","Ross Township"),
  ("Rosslyn Farms Borough","Rosslyn Farms Borough"),
  ("Scott Township","Scott Township"),
  ("Sewickley Borough","Sewickley Borough"),
  ("Sewickley Heights Borough","Sewickley Heights Borough"),
  ("Sewickley Hills Borough","Sewickley Hills Borough"),
  ("Shadyside","Shadyside"),
  ("Shaler Township","Shaler Township"),
  ("Sharpsburg Borough","Sharpsburg Borough"),
  ("Sheraden","Sheraden"),
  ("South Fayette Township","South Fayette Township"),
  ("South Oakland","South Oakland"),
  ("South Park Township","South Park Township"),
  ("South Shore","South Shore"),
  ("South Side Flats","South Side Flats"),
  ("South Side Slopes","South Side Slopes"),
  ("South Versailles Township","South Versailles Township"),
  ("Spring Garden","Spring Garden"),
  ("Spring Hill-City View","Spring Hill-City View"),
  ("Springdale Borough","Springdale Borough"),
  ("Springdale Township","Springdale Township"),
  ("Squirrel Hill North","Squirrel Hill North"),
  ("Squirrel Hill South","Squirrel Hill South"),
  ("St. Clair","St. Clair"),
  ("Stanton Heights","Stanton Heights"),
  ("Stowe Township","Stowe Township"),
  ("Strip District","Strip District"),
  ("Summer Hill","Summer Hill"),
  ("Swisshelm Park","Swisshelm Park"),
  ("Swissvale Borough","Swissvale Borough"),
  ("Tarentum Borough","Tarentum Borough"),
  ("Terrace Village","Terrace Village"),
  ("Thornburg Borough","Thornburg Borough"),
  ("Trafford Borough","Trafford Borough"),
  ("Troy Hill","Troy Hill"),
  ("Turtle Creek Borough","Turtle Creek Borough"),
  ("Upper Hill","Upper Hill"),
  ("Upper Lawrenceville","Upper Lawrenceville"),
  ("Upper St. Clair Municipality","Upper St. Clair Municipality"),
  ("Verona Borough","Verona Borough"),
  ("Versailles Borough","Versailles Borough"),
  ("Wall Borough","Wall Borough"),
  ("West Deer Township","West Deer Township"),
  ("West Elizabeth Borough","West Elizabeth Borough"),
  ("West End","West End"),
  ("West Homestead Borough","West Homestead Borough"),
  ("West Mifflin Borough","West Mifflin Borough"),
  ("West Oakland","West Oakland"),
  ("West View Borough","West View Borough"),
  ("Westwood","Westwood"),
  ("Whitaker Borough","Whitaker Borough"),
  ("White Oak Borough","White Oak Borough"),
  ("Whitehall Borough","Whitehall Borough"),
  ("Wilkins Township","Wilkins Township"),
  ("Wilkinsburg Borough","Wilkinsburg Borough"),
  ("Wilmerding Borough","Wilmerding Borough"),
  ("Windgap","Windgap"),
]